name: jupyterhub
version: 1.0
appVersion: 0.9.4
description: Multi-user Jupyter installation
home: https://z2jh.jupyter.org
sources:
  - https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/master/jupyterhub
icon: https://jupyter.org/assets/hublogo.svg
kubeVersion: '>=1.8.0-0'
tillerVersion: '>=2.9.1-0'
